name: Weekly Metrics
on:
  schedule: [{ cron: '0 8 * * FRI' }]
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - run: pnpm install --frozen-lockfile
      - run: |
          npx gh-pr-metrics ${{ secrets.METRICS_OWNER }}/${{ secrets.METRICS_REPO }} \
            --since 7d --format json --use-cache --resume \
            --token ${{ secrets.GH_TOKEN }} > metrics.json
      - name: Commit metrics
        uses: EndBug/add-and-commit@v9
        with:
          add: 'metrics.json'
          message: 'chore(metrics): weekly auto-update'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
